apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: software-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/llauderesv/homelab-gitops.git
    targetRevision: HEAD
    path: argocd-apps
    directory:
      recurse: true
      include: '{infrastructure}/*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true