apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-world
spec:
  hosts:
    - localhost
  http:
    - route:
        - destination:
            host: hello-world-service
            port:
              number: 3000
          weight: 100
